"""updates

Revision ID: 242f4c225422
Revises: 
Create Date: 2026-04-02 16:15:28.870748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242f4c225422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('treasury',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_levels',
    sa.Column('job_level_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('xp_required', sa.Integer(), nullable=False),
    sa.Column('promotes_to_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['promotes_to_job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_level_id')
    )
    op.create_table('citizens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_job_id', sa.Integer(), nullable=True),
    sa.Column('job_level_id', sa.Integer(), nullable=True),
    sa.Column('last_quit', sa.DateTime(), nullable=True),
    sa.Column('total_income', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['job_level_id'], ['job_levels.job_level_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bounties',
    sa.Column('bounty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'taken', 'completed', 'disputed'), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['citizens.user_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('bounty_id')
    )
    op.create_table('employment_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('hired_at', sa.DateTime(), nullable=True),
    sa.Column('quit_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('fines',
    sa.Column('fine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issued_to', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['issued_to'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('fine_id')
    )
    op.create_table('job_xp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('negotiation_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bounty_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.bounty_id'], ),
    sa.ForeignKeyConstraint(['proposed_by'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.BigInteger(), nullable=True),
    sa.Column('to_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('payment', 'tax', 'fine', 'treasury'), nullable=False),
    sa.Column('bounty_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.bounty_id'], ),
    sa.ForeignKeyConstraint(['from_id'], ['citizens.user_id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['citizens.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('negotiation_log')
    op.drop_table('wallets')
    op.drop_table('job_xp')
    op.drop_table('fines')
    op.drop_table('employment_log')
    op.drop_table('bounties')
    op.drop_table('citizens')
    op.drop_table('job_levels')
    op.drop_table('treasury')
    op.drop_table('jobs')
    # ### end Alembic commands ###
