"""empty message

Revision ID: 811bea06311a
Revises: b9ccb2e89b6f
Create Date: 2026-04-25 18:18:41.364410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811bea06311a'
down_revision: Union[str, Sequence[str], None] = 'b9ccb2e89b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounties', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bounties', 'jobs', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bounties', type_='foreignkey')
    op.drop_column('bounties', 'job_id')
    # ### end Alembic commands ###
