"""empty message

Revision ID: a787dd749335
Revises: 13a3f2ecc656
Create Date: 2026-05-07 00:42:35.609066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a787dd749335'
down_revision: Union[str, Sequence[str], None] = '13a3f2ecc656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('profile_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizens', 'profile_access')
    # ### end Alembic commands ###
